### ISSUE TITLE
EnterPress action doesn't work in DataGrid when opened a lot of tabs

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/sampler#16]
Steps to reproduce:
1. Open at least 8 tabs including **"ItemClick and EnterPress actions"** screen in DataGrid menu;
2. Select **"ItemClick and EnterPress actions"** screen;
3. Select row and press enter key;

**AR** Notification for entering press action doesn't appear.

**Comment by glebfox** [comment]
The issue won't be relevant after migration to Platform 7.0 (#21)
