### ISSUE TITLE
Change selection text color in suggestion field samples with options style provider

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/sampler#43]
Samples to change:
- [optionsstyleprovider-suggestionfield](https://demo.cuba-platform.com/sampler/#main/2/sample?id=optionsstyleprovider-suggestionfield)
- [optionsstyleprovider-suggestionpickerfield](https://demo.cuba-platform.com/sampler/#main/10/sample?id=optionsstyleprovider-suggestionpickerfield)

How it should be:
https://demo.cuba-platform.com/sampler/#main/11/sample?id=options-style-provider-lookupfield

**Comment by glebfox** [comment]
Possibly the issue relates to CUBA. The same styles work perfectly for `LookupField`.

**Comment by Flaurite** [comment]
Depends on: https://github.com/cuba-platform/cuba/issues/2613

**Comment by glebfox** [comment]
Related issue is fixed
